[package]
name = "javabox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.2", features = ["derive"] }
log = "0.4.17"
symlink = "0.1.0"
dir = "0.1.2"
url = "2.3.1"
ureq = "2.5.0"
zip-extract = "0.1.1"